### ISSUE TITLE
Diffusion model not capturing cyclical nature

### ISSUE THREAD

**Issue by OmegaAsh** [Y-debug-sys/Diffusion-TS#20]
Hi there, thanks for your work on this,

I am just using the model to generate some synthetic PPG signal data for a project (will be sure to cite), and it seems to perform quite good, although it isn't capturing the cyclical nature of the signals enough (e.g. too much variation between cycles) which is really important in this type of data.

Just wondering as you have used and tuned the model a lot, whether you know of any tricks to guide the model towards a more cyclical and uniform output? An example of my current output is shown below (original in blue, synthetic in yellow).

![graph](https://github.com/Y-debug-sys/Diffusion-TS/assets/60603397/cae2a728-b116-4019-9897-6f8829efc476)

Thanks again

**Comment by Y-debug-sys** [comment]
Hi, OmegaAsh.

On the one hand, due to using MLP to build the main network, it's prone to overfitting, so you can try adding a bit of dropout ratio in config.
 
On the other hand, please check your dataset. I just downloaded a PPG dataset from https://zenodo.org/records/3902676 and ploted out the following sequence of a feature. 
![p1](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/78f91bfc-42a6-4740-a33b-52b3f15a5579)

It shows that its periodicity actually varies over time (your synthetic curve are more similar to the front part, while the real sequences you chose to plot are more like the latter segment). So in my opinion, this is actually a probability issue depending on your dataset. 

Thanks !

**Comment by OmegaAsh** [comment]
Hi just want to verify this did seem to give better results. Thanks for your help!
