### ISSUE TITLE
About result of mujoco MSE

### ISSUE THREAD

**Issue by yanghu819** [Y-debug-sys/Diffusion-TS#56]
<img width="747" alt="image" src="https://github.com/user-attachments/assets/5b1f99be-02b4-4a05-a84c-106d57121732">
<img width="548" alt="image" src="https://github.com/user-attachments/assets/7a092876-32f2-4462-9b04-34765e2caca7">
How can I have result like 0.37(3) from this jupyter?

**Comment by Y-debug-sys** [comment]
Is there any problem? The performance in the demo is better than in the paper because the parameters were not carefully selected during our early experiments. Besides, the specific random seeds and model parameters were not saved at that time. Perhaps you can try standardization-normalization (but disable the clamp operation during the generation process).

**Comment by yanghu819** [comment]
thank you for so quick answering, so the result of 0.37(3) should be 0.00027 if the paper is updated，am I understanding right?

**Comment by Y-debug-sys** [comment]
You can understand it that way, but the results in the paper are the average of multiple experiments. Thanks!
